spring.application.name=SpringBootDynamoDbLocal

server.port=8080

#Dynamo local properties
dynamodb.local.port=8000
dynamodb.local.db-path=${user.home}/dynamodb-local-data

logging.level.com.rm.sbddl=DEBUG